project:
  type: website

website:
  page-navigation: true
  title: "Policy Comp Foundations"
  description: "Homepage for Computational Foundations for Policy Analysis: Programming and Reproducible Methods"
  site-url: "https://PolicyCompFoundations.github.io/website/"

  repo-url: https://github.com/PolicyCompFoundations/website
  repo-actions: [edit, issue]

  open-graph: true


  page-footer:
    left: "&copy; Copyright 2023, Jacob Jameson & Madison Coots"
    background: "#e6e6fa"

  sidebar:
    background: "#e6e6fa"
    logo: "assets/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/PolicyCompFoundations
        text: "GitHub organization"
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
      - section: "Setting Up"
        contents:
          - href: setup/mac-setup.qmd
            text: Mac OS Setup
          - href: setup/windows-setup.qmd
            text: Windows Setup

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual